ThirdHomework
AndrisP11/Home-exercises pull request #3
Opened 2022-09-20 04:41 UTC by AndrisP11

2022-10-18 11:58 UTC, NilsKula requested changes

2022-10-18 11:58 UTC, NilsKula commented on Home-exercises/src/main/java/io/codelex/arrays/practice/TicTacToe.java
> +    public static char checkWinner() {
private

2022-10-18 11:58 UTC, NilsKula commented on Home-exercises/src/main/java/io/codelex/classesandobjects/practice/Exercise10/BankAccount.java
> +        this.balance = this.balance + amount;
var saīsināt ar `+=`

2022-10-18 11:58 UTC, NilsKula commented on Home-exercises/src/main/java/io/codelex/classesandobjects/practice/Exercise10/BankAccount.java
> +        DecimalFormat f = new DecimalFormat("#,###.00",
neizmanto viena burta apzīmējumus

2022-10-18 11:58 UTC, NilsKula commented on Home-exercises/src/main/java/io/codelex/classesandobjects/practice/Exercise2/Car.java
> +    double startKilometers;
private

2022-10-18 11:58 UTC, NilsKula commented on Home-exercises/src/main/java/io/codelex/classesandobjects/practice/Exercise2/Car.java
> +        return this.calculateConsumption() > 15.0;
konstante

2022-10-18 11:58 UTC, NilsKula commented on Home-exercises/src/main/java/io/codelex/classesandobjects/practice/Exercise2/LitersPerKilometer.java
> +    public static double setStartKilometers() {
slikts naming, metodes ietvaros neko neesi setojis

2022-10-18 11:58 UTC, NilsKula commented on Home-exercises/src/main/java/io/codelex/classesandobjects/practice/Exercise3/OdometerTest.java
> +                    if (fuelGouge1.getFuel() + fuelUpOrNot < 0 || fuelGouge1.getFuel() + fuelUpOrNot > 70) {
šo jau varētu uz palīgmetodi

2022-10-18 11:58 UTC, NilsKula commented on Home-exercises/src/main/java/io/codelex/classesandobjects/practice/Exercise4/Movie.java
> +    String title;
private

2022-10-18 11:58 UTC, NilsKula commented on Home-exercises/src/main/java/io/codelex/classesandobjects/practice/Exercise7/Dog.java
> +        boolean b = this.mother.equals(mother);
nedaudz liekas rindiņas
`returrn this.mother.equals(mother)`

2022-10-20 11:43 UTC, janistumpelis approved these changes

2022-10-20 13:30 UTC, merged